// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('windSpeed', { text: '13' });
    CreateText('outsideRelativeHumidityBox', { text: 'Text' });
    CreateText('RH', { text: unescape('%25  RH') });
    CreateText('MPH', { text: 'MPH' });
    CreateShape('roundedRectangleShape1', { rightImageWidth: 10, leftImageWidth: 10 });
    CreateShape('roundedRectangleShape', { rightImageWidth: 10, leftImageWidth: 10 });
    CreateShape('roundedRectangleShape2', { rightImageWidth: 1, leftImageWidth: 1 });
    CreateText('outsideTempBox', { text: 'Text' });
    CreateShape('roundedRectangleShape7', { rightImageWidth: 10, leftImageWidth: 10 });
    CreateShape('roundedRectangleShape8', { rightImageWidth: 10, leftImageWidth: 10 });
    CreateShape('roundedRectangleShape9', { rightImageWidth: 10, leftImageWidth: 10 });
    CreateShape('roundedRectangleShape10', { rightImageWidth: 1, leftImageWidth: 1 });
    CreateShape('roundedRectangleShape11', { rightImageWidth: 10, leftImageWidth: 10 });
    CreateText('insideTempBox', { text: 'Text' });
    CreateText('insideRelativeHumidityBox', { text: 'Text' });
    CreateText('RH1', { text: unescape('%25  RH') });
    CreateText('INSIDE', { text: 'INSIDE' });
}
window.addEventListener('load', setupParts, false);
